services:
  mongo:
    image: mongo:latest
    container_name: telemetry_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto
    container_name: telemetry_mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf

  adapter:
    build: ./adapter
    container_name: telemetry_adapter
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - PORT=3000
    depends_on:
      - mongo
      - mosquitto

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_WS_URL=${VITE_WS_URL}
    container_name: telemetry_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - adapter

volumes:
  mongo_data:
  mosquitto_data:
  mosquitto_log: